[package]
name = "tonbo-python"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
fusio = { git = "https://github.com/tonbo-io/fusio.git", package = "fusio", rev = "317b1b0621b297f52145b41b90506632f2dc7a1d", features = [
    "tokio",
    "dyn",
] }
futures = { version = "0.3" }
pyo3 = { version = "0.21.2", features = [
    "extension-module",
    "abi3",
    "abi3-py310",
] }
pyo3-asyncio = { package = "pyo3-asyncio-0-21", version = "0.21", features = [
    "tokio-runtime",
] }
tokio = { version = "1", features = ["rt-multi-thread"] }
tonbo = { version = ">=0", path = "../../" }
