[package]
description = "TonboRecord macro"
documentation = "https://docs.rs/tonbo_marcro"
edition = "2021"
license = "Apache-2.0"
name = "tonbo_macro"
version = "0.1.0"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "2"

[lib]
path = "src/lib.rs"
proc-macro = true
